### PR TITLE
Set up eslint with prettier

### PR DESCRIPTION
**Pull request by chronark**
I have tried to retain @fauna-brecht configuration where possible.
The prettier rules are the same as before and eslint rules.

I wanted to get it passing first so I changed a few rules to `warning`.

Minor issues are fixed in the next commit.
The .eslintrc.js file contains some more annotation about next steps.

Use `npm run fmt` to run eslint and prettier.

Let me know what you think. This is just how I would set it up but some

things are debatable ;)

### CODE REVIEW

**Comment by chronark** [comment]
Noteworthy: For me the tests don't pass, but they did not pass before either.

```sh
npm run test

> fauna-schema-migrate@2.0.0 test
> ava -T 200s --fail-fast


  ✖ isPlainObject is not a function
  ```
  that function seems to be coming from lodash but that's as far as I have traced it.

**Comment by ptpaterson** [comment]
Brecht has the project set at `tabWidth: 4`

**Comment by fauna-brecht** [comment]
Thanks for the suggestions, I'll look into it om Monday since I had quite a
busy day. I agree it's needed, I typically am keen on setting this up
whenever I star a repo and somehow didn't for this one ;)

**Comment by chronark** [comment]
> Brecht has the project set at `tabWidth: 4`

I literally copied the prettier config out of `.eslintrc.js` in the master branch, I don't know where `tabWidth` would have been set, but either way that can be added easily.

**Comment by fauna-brecht** [comment]
> Noteworthy: For me the tests don't pass, but they did not pass before either.
> 
> ```shell
> npm run test
> 
> > fauna-schema-migrate@2.0.0 test
> > ava -T 200s --fail-fast
> 
> 
>   ✖ isPlainObject is not a function
> ```
> 
> that function seems to be coming from lodash but that's as far as I have traced it.

I'm guessing you just went back to master but did not drop the node_modules folder when you say that it didn't work before either. It seems to be introduced by the libraries that were introduces for linting which is surprising but that seems to be the case. I run the tests when I push and the tests are ran automatically in GitHub actions as well so am certain that they ran before. After installing the extra dependencies it no longer worked. When going back to master and dropping node_modules it worked again so I'm guessing a library conflict.

**Comment by fauna-brecht** [comment]
Hey, 

went through it, changed some minor things and made sure that tests run (at least on my end they do).
https://github.com/fauna-brecht/fauna-schema-migrate/tree/pullrequest%2317

Changed:
- removed yarn comment, until now we don't use yarn.
- went further and added eslint-config-standard which is what I typically use
- ignored dist completely, is there a reason we would lint built files? 
- resolved a number of errors and warnings 

We do have a number of warnings still on 'any' and 'explicit return types'. The 'any' were meant to save time, custom types that are currently used can use some love overall, but I currently don't have time to go through all of this since I'm juggling many things at once. I'm overall ok with these rules but wouldn't like contributors to be bombarded with warnings, so I'm considering ignoring those entirely for now. Thoughts?

**Comment by chronark** [comment]
Thanks.
My bad on the yarn stuff, I usually use yarn and didn't think twice when I copied it :D

Testing on my machine is still a bit weird and throwing errors but that's on me. It runs fine inside a node:14 container

About the remaining `any` etc. issues:
I kind of dislike ignoring them globally because that just allows new `any`s to be introduced.
Maybe ignoring them on a per line basis and create an issue to keep track of fixing them? That's not really a perfect solution but the best I got.

**Comment by fauna-brecht** [comment]
> I kind of dislike ignoring them globally because that just allows new `any`s to be introduced.
> Maybe ignoring them on a per line basis and create an issue to keep track of fixing them? That's not really a perfect solution but the best I got.

I personally don't feel that strongly about 'any' for small projects since I tend to limit typing to where it actually helps me. Since I see many pull requests incoming which means I'm no longer working alone. Then it definitely makes sense to have stronger typing. Adding ignores everywhere is also introducing work of course. Currently, I can't prioritize improving the code in such a way over my other tasks. Let's just keep an issue open and keep the warnings for now.

**Comment by chronark** [comment]
Sure sounds good.
Do you want to just merge your branch and delete mine? Or how would you move forward with this?

**Comment by fauna-brecht** [comment]
Should be merged via the other pull request but was not detected by github

**Pull request closed without merging**
