### PR TITLE
Detect and parse .ts files just like .js

### PR DESCRIPTION
**Pull request by chronark**

### CODE REVIEW

**Comment by chronark** [comment]
This works pretty much exactly like with `.js` files
It compiles them using esbuild and the rest of the steps are the same.

**Comment by ptpaterson** [comment]
Not a technical comment, but a formatting one:  Brecht has got indentation set to 4 spaces.  The commit is confused with all of the formatting changes, too.

On that note, I think that enforcing the formatting would be good.  @fauna-brecht prettier default tab width is 2 spaces.  Do you have a different setting in your editor?  Anyways... can add `tabWidth: 4` to eslint

https://github.com/fauna-brecht/fauna-schema-migrate/blob/7aeebc4d5313435d723f7df16421add400a642fc/.eslintrc.js#L25-L29

**Comment by chronark** [comment]
Yes I was talking to him in slack about that already. I didn't see an npm script for linting and assumed there was nothing set up.
I accidentally ran my default formatter and then manually reverted it (or at least I thought I did).

And to be honest I am having trouble running eslint without a script.
`npx eslint  . ` complains about missing `prettier-standard` even though it is set as dev dependency

I'll go try some more things. But I agree, a standard is important.

**Comment by chronark** [comment]
Right, after installing the missing dependencies I believe this repo has never been linted before :D
It'll take some time to resolve those issues.

**Comment by chronark** [comment]
Hmm as you can see in the last commit, the code before was not standardized either. If anything that made the commit even worse to read :D

**Comment by ptpaterson** [comment]
lol will see what Brecht says!  Could hard revert and commit with 0 formatting changes, but if it's working... 🤷 😋 

I'd help PR for using not-global eslint and doing nothing but a complete lint later tonight.  I'm mostly  musing myself in the comments but can't spend time on actual code for like another 8 hours 🙃

**Comment by chronark** [comment]
@ptpaterson  @fauna-brecht I created a PR for the linting/formatting #17

**Comment by fauna-brecht** [comment]
I typically set up linting when I start a project, but this project was originally a fork from Bruno's tool so I didn't set it up from scratch. In the end it barely has any resemblance with the original fork but I completely forgot to add linting. When there is no linter present in a project, VS code indeed has some things set up to do some basic formatting. To avoid bikeshedding I applaud this pull request and make sure there is a standard. Looking into it now.

**Comment by fauna-brecht** [comment]
Looks great, I added it as a commit on https://github.com/fauna-brecht/fauna-schema-migrate/tree/pullrequest%2317 and added a very rudimentary test. 

I would normally not combine two pull requests but in this case it was much easier to review once the linting was more or less aligned :)

**Comment by chronark** [comment]
Yeah that became quite a messy commit.
Looks good to me.

**Pull request merged**
